const os = require('os')

// const.log(os)
// console.log(os.platform())
// console.log(os.version())
// console.log(os.cpus())
// console.log(os.homedir())
// console.log(os.freemem())
// console.log(os.userInfo())
// console.log(os.machine())
console.log(os.totalmem())